parameters:
#    acme_facebook.example.class: Acme\FacebookBundle\Example

services:
    acme_facebook.component.facebook_user_page_paginator:
        class: Acme\FacebookBundle\Component\FacebookUserPagePaginator
        arguments: ["@doctrine.orm.entity_manager", "@knp_paginator", 3 ]
    acme_facebook.component.acme_facebook_component:
        class: Acme\FacebookBundle\Component\AcmeFacebookComponent
        arguments: [ @doctrine.orm.entity_manager, @fos_facebook.api ]
    acme_facebook.component.security.auth_success_handler:
        class: Acme\FacebookBundle\Component\Security\AuthSuccessHandler
        arguments: [@router, %acme_facebook.redirect_after_login_success_url%, @acme_facebook.component.acme_facebook_component ]
    acme_facebook.admin.facebook_feed_admin:
        class: Acme\FacebookBundle\Admin\FacebookFeedAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: acme_facebook, label: FacebookFeed }
        arguments: [null, Acme\FacebookBundle\Entity\FacebookFeed, SonataAdminBundle:CRUD]
    acme_facebook.twig.facebook_extension:
        class: Acme\FacebookBundle\Twig\Extension\FacebookExtension
        arguments: [ @doctrine.orm.entity_manager ]
        tags:
            - { name: twig.extension, alias: facebook_extension }