parameters:
#    acme_assortment.example.class: Acme\AssortmentBundle\Example

services:
#    acme_assortment.example:
#        class: %acme_assortment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    acme_assortment.admin.category:
        class: Acme\AssortmentBundle\Admin\AssortmentCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: acme_assortment, label: Categories }
        arguments: [null, Acme\AssortmentBundle\Entity\AssortmentCategory, SonataAdminBundle:CRUD, @doctrine.orm.entity_manager, AcmeAssortmentBundle:AssortmentCategory, AcmeAssortmentBundle:FrontEndAssortmentCategory:assortmentCategoryView ]
    acme_assortment.admin.page:
        class: Acme\AssortmentBundle\Admin\AssortmentPageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: acme_assortment, label: Assortment pages }
        arguments: [null, Acme\AssortmentBundle\Entity\AssortmentPage, SonataAdminBundle:CRUD, @doctrine.orm.entity_manager, AcmeAssortmentBundle:AssortmentPage, AcmeAssortmentBundle:FrontEndAssortmentPage:assortmentPageView ]
    acme_assortment.admin.page_has_admin:
        class: Acme\AssortmentBundle\Admin\AssortmentPageHasMediaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: acme_assortment, show_in_dashboard: false, label: page_has_admin }
        arguments: [null, Acme\AssortmentBundle\Entity\AssortmentPageHasMedia, SonataAdminBundle:CRUD]
    acme_assortment.sonata_model_list_type_thumb_form:
        class: Acme\AssortmentBundle\Form\Type\ModelThumbListType
        tags:
            -  { name: form.type, alias: sonata_type_model_list_thumb }
    acme_assortment.menu.assortment_category_menu_builder:
        class: Acme\AssortmentBundle\Menu\AssortmentCategoryMenuBuilder 
        arguments: ["@knp_menu.factory", "@doctrine.orm.entity_manager","@security.context"]
    acme_assortment.component.assortment_category_component:
        class: Acme\AssortmentBundle\Component\AssortmentCategoryComponent
        arguments: [ "@doctrine.orm.entity_manager", "@sonata.seo.page" , "@service_container" ]
    acme_assortment.component.assortment_page_component:
        class: Acme\AssortmentBundle\Component\AssortmentPageComponent
        arguments: [ "@doctrine.orm.entity_manager", "@sonata.seo.page" , "@service_container" ]
    acme_assortment.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: acme_assortment.menu.assortment_category_menu_builder
        factory_method: createAssortmentCategoryMenu
        arguments: ["@request", "assortment-menu vertical-list"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: assortmentCategory } # The alias is what is used to retrieve the menu
    acme_assortment.component.assortment_page_paginator:
        class: Acme\AssortmentBundle\Component\AssortmentPagePaginator
        arguments: ["@doctrine.orm.entity_manager", "@knp_paginator", 3 ]
    acme_assortment.twig.extension.assortment_extension:
        class: Acme\AssortmentBundle\Twig\Extension\AssortmentExtension
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: twig.extension, alias: assortment_extension }