parameters:
#    acme_fancy.example.class: Acme\FancyBundle\Example

services:
#    acme_fancy.example:
#        class: %acme_fancy.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
