<?php

namespace Acme\AssortmentBundle\Entity;
use Acme\TreeBundle\Entity\TreeRepository;
use Doctrine\ORM\EntityRepository;

/**
 * AssortmentCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssortmentCategoryRepository extends TreeRepository
{
}
