
#jmi_site_:
#    path:      /{culture}
#    defaults:  { _controller: AcmeDemoBundle:Main:homepage, culture: en }
#    requirements:
#        culture:  en|fr
#
#jmi_site_:
#    prefix: /admin
#    resource: "@JMISiteBundle/Resources/config/routing.xml"




#jmi_site_reference:
#    prefix:   /reference
#    resource: "@JMISiteBundle/Controller/ReferenceController.php"
#    type:     annotation



#jmi_site_media_view:
#    path:      "/slike/{id}/{format}"
#    defaults:  { _controller: SonataMediaBundle:Media:view, format: jpg }
#jmi_site_reference_gallery:
#    path:      "/slike/{id}/{format}"
#    defaults:  { _controller: SonataMediaBundle:Media:view, format: jpg }



