
#jmi_site_:
#    path:      /{culture}
#    defaults:  { _controller: AcmeDemoBundle:Main:homepage, culture: en }
#    requirements:
#        culture:  en|fr
#
#jmi_site_:
#    prefix: /admin
#    resource: "@JMISiteBundle/Resources/config/routing.xml"




t2_domene_home:
    path:      /
    defaults:  { _controller: JMISiteBundle:Default:oPodjetju, culture: si }

t2_domene_home:
    path:      /storitve
    defaults:  { _controller: JMISiteBundle:Default:storitve, culture: si }

jmi_site_reference:
    prefix:   /reference
    resource: "@JMISiteBundle/Controller/ReferenceController.php"
    type:     annotation


#jmi_site_media_view:
#    path:      "/slike/{id}/{format}"
#    defaults:  { _controller: SonataMediaBundle:Media:view, format: jpg }
#jmi_site_reference_gallery:
#    path:      "/slike/{id}/{format}"
#    defaults:  { _controller: SonataMediaBundle:Media:view, format: jpg }



# Gallery bundle
#sonata_media_gallery:
#    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
#    prefix: /media/gallery
#
#sonata_media_media:
#    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
#    prefix: /media
#
#sonata_media_pixlr:
#    resource: '@SonataMediaBundle/Resources/config/routing/pixlr.xml'
#    prefix: /admin/media


