parameters:
#    acme_contact.example.class: Acme\ContactBundle\Example

services:
#    acme_contact.example:
#        class: %acme_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    acme_contact.form.type.contact_form_type:
        class: Acme\ContactBundle\Form\Type\ContactFormType
    acme_contact.block.service.google_map:
        class: Acme\ContactBundle\Block\GoogleMapBlockService
        tags:
            - {name: "sonata.block"}
        arguments: [acme_contact.block.service.google_map, @templating]
    acme_contact.block.service.contact_form:
        class: Acme\ContactBundle\Block\ContactFormBlockService
        tags:
            - {name: "sonata.block"}
        arguments: [acme_contact.block.service.contact_form, @templating, @service_container]