acme_el_finder_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeElFinderBundle:Default:index }
ef_connect:
    pattern:  /efconnect
    defaults: { _controller: FMElfinderBundle:Elfinder:load }
elfinder_extended:
    pattern: /elfinder-extended
    defaults: { _controller: AcmeElFinderBundle:Elfinder:showExtended }
elfinder:
    pattern: /elfinder
    defaults: { _controller: FMElfinderBundle:Elfinder:show }
