parameters:
#    acme_el_finder.example.class: Acme\ElFinderBundle\Example

services:
#    acme_el_finder.example:
#        class: %acme_el_finder.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    acme_el_finder.twig.acme_extension:
        class: Acme\ElFinderBundle\Twig\Extension\FMElfinderTinymceExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension, alias: fm_tinymce_init_extended }