# src/Acme/MainLogicBundle/Resources/config/validation.yml
Acme\FormBundle\Entity\Form:
    properties:
        action:
            - NotBlank: { groups: [hause_type, flat_type, local_type, parcel_type, storage_type] }
        type:
            - NotBlank: { groups: [hause_type, flat_type, local_type, parcel_type, storage_type] }
        area:
            - NotBlank: { groups: [hause_type, flat_type, local_type, parcel_type, storage_type] }
        localization:
            - NotBlank: { groups: [hause_type, flat_type, local_type, parcel_type, storage_type] }
        buildingType:
            - NotBlank: { groups: [hause_type] }
        roomsCount:
            - NotBlank: { groups: [hause_type, flat_type, local_type] }
        priceMax:
            - NotBlank: { groups: [hause_type, flat_type] }
        pricePerMeterMax:
            - NotBlank: { groups: [local_type, storage_type] }
        storey:
            - NotBlank: { groups: [flat_type, local_type] }
        blockType:
            - NotBlank: { groups: [flat_type] }
        standard:
            - NotBlank: { groups: [flat_type] }
        propertyType:
            - NotBlank: { groups: [parcel_type] }
        media:
            - NotBlank: { groups: [parcel_type] }
        loadingRamp:
            - NotBlank: { groups: [storage_type] }
        maneuverField:
            - NotBlank: { groups: [storage_type] }
        email:
            - NotBlank: { groups: [hause_type, flat_type, local_type, parcel_type, storage_type] }
            - Email: { checkHost: true, groups: [hause_type, flat_type, local_type, parcel_type, storage_type] }