parameters:
#    acme_tiny_mce.example.class: Acme\TinyMceBundle\Example

services:
#    acme_tiny_mce.example:
#        class: %acme_tiny_mce.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    acme_tiny_mce.twig.acme_tinymce:
        class: Acme\TinyMceBundle\Twig\Extension\TinyMceBundleExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension, alias: tinymce_extension }
